### ISSUE TITLE
issue on FFA-IR(FFA) dataset

### ISSUE THREAD

**Issue by cheliu-computation** [lxirich/MM-Retinal#1]
Dear Authors,

Thanks for your impressive work!

When I check the dataset of FFA-IR(FFA), the physionet show this project has no data now.
May I ask where did you collect this data?

**Comment by lxirich** [comment]
Thank you for your inquiry about the FFA-IR dataset. The original authors have disabled the download links due to policy changes, as noted on PhysioNet.

Therefore, we cannot provide the dataset directly. Please consider contacting the original authors to request access, or ask others who have previously downloaded it. If you get approval from the original authors, we can then provide it to you.

**Comment by cheliu-computation** [comment]
Thanks for your reply. I will contact to original authors.
